config/routes.rb
require 'resque/server'

Reciplease::Application.routes.draw do
  # see config.ru for authentication setup
  mount Resque::Server.new, :at => "/resque"

  authenticated :user do
    root :to => 'recipes#index'

    # RECIPES
    # => only accessible to authenticated users
    get "/recipes", :to => "recipes#index", :as => "recipes"
    post "/recipes", :to => "recipes#create"

    get "/recipes/new", :to => "recipes#new", :as => "new_recipe"

    get "/recipes/:id/edit", :to => "recipes#edit", :as => "edit_recipe"

    get "/recipes/:id", :to => "recipes#show", :as => "recipe"
    put "/recipes/:id", :to => "recipes#update"
    delete "/recipes/:id", :to => "recipes#destroy"
  end

  root :to => "home#index"

  get "/recipes", :to => "home#index"
  get "/recipes/:id", :to => "home#index"

  devise_for :users
  resources :users
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  attr_accessible :amount, :food, :text, :unit

  belongs_to :recipe
end

app/models/recipe.rb
require 'ingreedy'

class Recipe < ActiveRecord::Base
  attr_accessible(
    :author,
    :description,
    :instructions,
    :name,
    :published_on,
    :ingredients_text,
    :document_cache,
    :ocr_raw_text,
    :source,
    :ocr_processed
  )

  mount_uploader :document, RecipeDocumentUploader

  validates :name, :user, presence: true
  # validate :manual_or_document_creation

  # def manual_or_document_creation
  #   if !document.present?
  #     # no document present, so was created manually
  #     # => ingredients_text and instructions can't be blank
  #     errors.add(:ingredients_text, "Ingredients can't be blank") if ingredients_text.blank?
  #     errors.add(:instructions, "Instructions can't be blank") if instructions.blank?
  #   end
  # end

  has_many :ingredients
  belongs_to :user



  def parse_ingredient_text(text_to_parse)
    items = text_to_parse.split(/\s*\n+\s*/)
    ingredients = Array.new
    items.each do |item|
      ingredient = Hash.new(amount: nil, food: nil, text: nil, unit: nil)
      parsed = Ingreedy.parse(item)
      ingredient[:amount] = parsed.amount
      ingredient[:food] = parsed.ingredient
      ingredient[:unit] = parsed.unit
      ingredient[:text] = item
      ingredients << ingredient
    end

    ingredients
  end

  def add_ingredients_from_text(text_to_parse)
    ingredients_ary = parse_ingredient_text(text_to_parse)
    ingredients_ary.each do |ingredient|
      self.ingredients.create(
        amount: ingredient[:amount],
        food: ingredient[:food],
        text: ingredient[:text],
        unit: ingredient[:unit]
      )
    end
  end

  def add_ingredients_from_self
    add_ingredients_from_text(ingredients_text)
  end


  # these need to be in this order!
  # after_save :async_create_from_document
  after_save :update_ingredients_from_text

  # def update_ingredients_from_document
  #   # if @ocr_done is not set, this may run in an infinite loop,
  #   # as document_changed? will be true after the first run
  #   # ('save' at the bottom triggers this method again)
  #   if document_changed? && !@ocr_done
  #     # run ocr stuff
  #     # placeholder: just set ingredients_text and instructions
  #     self.ingredients_text = "Created from document\n1 egg\n5 cups sugar\n12 sticks butter"
  #     self.instructions = "Created from document. Here are the instructions!"
  #     @ocr_done = true
  #     save
  #   end
  # end

  def update_ingredients_from_text
    # when creating a new instance, a form could send an empty string
    # as a value for ingredients_text, which would set ingredients_text_changed?
    # to true (it was previously nil). Ensure that we don't process this.
    if ingredients_text_changed? && !ingredients_text.blank?
      # manual ingredient entry. parse it out into Ingredient objects
      add_ingredients_from_self
    end
  end

  # this should only be called from async_create_from_document
  # or processing will probably hang
  # def create_from_document
  #   if !@ocr_done
  #     self.instructions = "Created from #{self.document.sanitized_file.filename}"
  #     @ocr_done = true
  #     save
  #   end
  # end

  def async_create_from_document
    Resque.enqueue(OCRProcessor, self.id)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.order("created_at DESC").limit(10)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @recipes = current_user.recipes
  end

  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html { }
      format.json { render json: @recipe }
    end
  end

  def edit
    recipe = Recipe.find(params[:id])
    if current_user.recipes.include? recipe
      @recipe = recipe
    else
      redirect_to recipes_url
    end
  end

  def new
    if !params[:recipe].nil? && !params[:recipe].empty?
      @recipe = Recipe.new(params[:recipe])
    else
      @recipe = Recipe.new
    end
  end

  def create
    @recipe = Recipe.new(params[:recipe].except(:document))
    # attach to the current user
    @recipe.user = current_user
    @recipe.document = params[:recipe][:document]

    respond_to do |format|
      if @recipe.save

        # asynchronously fill out recipe object from the document
        if @recipe.document.present?
          @recipe.async_create_from_document
        end

        format.html do
          redirect_to @recipe, notice: "<b>#{@recipe.name}</b> has been added!".html_safe
        end
        format.json do
          render json: @recipe, status: :created, location: @recipe
        end
      else
        format.html do
          flash[:error] = "Error saving recipe."
          render action: "new"
        end
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/:id
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe].except(:document))
        format.html { redirect_to @recipe, notice: "<b>#{@recipe.name}</b> has been updated!".html_safe }
        format.json { render json: @recipe }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end

  end


  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    recipe = Recipe.find(params[:id])
    if current_user.recipes.include? recipe
      recipe.destroy
      respond_to do |format|
        format.html { redirect_to recipes_url }
        format.json { head :no_content }
      end
    else
      redirect_to recipes_url
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/home/index.html.erb
<div class="hero">
  <h1>Welcome to Reciplease.</h1>
</div>

<div class="recent-recipes">
  <h3>Recently Created Recipes</h3>
  <% if @recipes.empty? %>
    <p>None! Save a recipe or two.</p>
  <% else %>
    <p><%= @recipes.map(&:name).join(", ") %></p>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<% if current_user %>
  <footer class="main-footer">
    <p>Eat food, not too much, mostly plants.</p>
  </footer>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Reciplease", root_path, :class => 'brand' %>
<ul class="nav" style="float: right;">

  <% if user_signed_in? %>
    <li>
      <%= link_to "Recipes", recipes_path %>
    </li>
    <li>
      <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <li>
      <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
      <%= link_to 'Login', new_user_session_path %>
    </li>
    <li>
      <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Reciplease" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Reciplease" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <script type="text/javascript" src="<%= request.protocol %>use.typekit.net/ofb1fib.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/recipes/edit.html.erb
<h1>Recipes#edit</h1>
<p>Find me in app/views/recipes/edit.html.erb</p>

app/views/recipes/index.html.erb
<h3 style="float: left;">Recipes</h3>
<div class="new-recipe-button"><%= link_to "New Recipe", new_recipe_path, :class => "btn btn-primary" %></div>

<br style="clear: both;">

<% if @recipes.empty? %>
  <h4>You don't have any recipes yet! Why don't you <%= link_to "create one now?", new_recipe_path %></h4>
<% else %>
  <% @recipes.each_with_index do |recipe, index| %>

    <% # new row every N * 4 recipes %>
    <% if (index) % 32 == 0 %>
      <div class="row-fluid recipe-row">
    <% end %>

      <% # columns every N recipes %>
      <% if (index) % 8 == 0 %>
        <div class="span3">
          <ul class="recipes">
      <% end %>

            <li>
              <%= link_to recipe.name, recipe %>
            </li>

      <% if (index - 7) % 8 == 0 || (index + 1) == @recipes.size %>
          </ul>
        </div>
      <% end %>

    <% if (index - 31) % 32 == 0 || (index + 1) == @recipes.size %>
      </div>
    <% end %>

  <% end %>

<% end %>

<p class="light"><%= @recipes.size %> total recipes</p>

app/views/recipes/new.html.erb
<h3 style="margin-bottom: 20px;">Add a Recipe</h3>

<% if @recipe.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @recipe.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<ul class="nav nav-tabs">
  <li class="active"><a href="#take_a_photo" data-toggle="tab">Take a Photo</a></li>
  <li><a href="#write_your_own" data-toggle="tab">Write Your Own</a></li>
</ul>

<div class="tab-content">

  <div class="tab-pane active" id="take_a_photo">
    <%= form_for @recipe, :multipart => true do |f| %>

      <fieldset>
        <legend>Take a Photo of a Printed Recipe</legend>
        <div>
          <%= f.label :name %>
          <%= f.text_field :name, :placeholder => "e.g. Alice Water's Banana Bread" %>
        </div>

        <div>
          <%= image_tag(@recipe.document.thumb.url) if @recipe.document? %>
          <div id="file-name"><%= @recipe.document? ? @recipe.document.identifier : "" %></div>
          <div>
            <%= f.file_field :document, :id => "file-input" %>
            <button id="file-button" class="btn">
              <%= @recipe.document? ? "Choose a different photo" : "Choose image/take photo" %>
            </button>
            <%= f.hidden_field :document_cache %>
          </div>
        </div>
      </fieldset>

      <div style="margin-top:20px;"><%= f.submit "Add Recipe", :class => "btn btn-primary" %></div>

    <% end %>
  </div>

  <div class="tab-pane" id="write_your_own">
    <%= form_for @recipe do |f| %>

      <fieldset>
        <legend>Basic Info</legend>
        <div>
          <%= f.label :name %>
          <%= f.text_field :name, :placeholder => "e.g. Alice Water's Banana Bread" %>
        </div>

        <div>
          <%= f.label :author %>
          <%= f.text_field :author, :placeholder => "e.g. Mom, Alice Waters, etc." %>
        </div>

        <div>
          <%= f.label :published_on, "Date Published" %>
          <%= f.text_field :published_on, :type => "date" %>
        </div>

        <div>
          <%= f.label :description, "Short Description" %>
          <%= f.text_area :description, :placeholder => "e.g. The best banana bread EVAR!", :size => "24x3" %>
        </div>
      </fieldset>

      <fieldset>
        <legend>Ingredients &amp; Recipe Steps</legend>
        <div>
          <%= f.label :ingredients_text, "Ingredients" %>
          <%= f.text_area :ingredients_text, :placeholder => "e.g. 3-4 ripe bananas, mashed; 1 egg; 3/4 cup sugar; etc.", :size => "40x15" %>
        </div>
        <div>
          <%= f.label :instructions %>
          <%= f.text_area :instructions, :placeholder => "e.g. Preheat the oven to 350 degrees. Mix in the ingredients in a bowl. ... etc.", :size => "40x15" %>
        </div>
      </fieldset>

      <div style="margin-top:20px;"><%= f.submit "Add Recipe", :class => "btn btn-primary" %></div>

    <% end %>
  </div>

</div>

app/views/recipes/show.html.erb
<div class="recipe-container" data-id="<%= @recipe.id %>">

<div class="recipe-basics">

  <h3><%= @recipe.name.blank? ? "Unnamed Recipe" : @recipe.name %></h3>
  <% unless @recipe.author.blank? %>
    <p>by <%= @recipe.author %></p>
  <% end %>

  <!-- <p>Published On: <%= @recipe.published_on.blank? ? "blank!" : @recipe.published_on %></p> -->

  <% unless @recipe.description.blank? %>
    <p><%= simple_format(@recipe.description) %></p>
  <% end %>

  <% unless @recipe.document.blank? %>
    <%= link_to @recipe.document.url do %>
      <img src="<%= @recipe.document.url %>">
    <% end %>
    <!-- <p><%= link_to "View Original", @recipe.document.url %></p> -->
  <% end %>

</div>

<div class="ingredients-instructions">

<p class="info-box" style="display: none; width: 300px; margin: 0 auto; text-align: center;"></p>

  <% unless @recipe.ingredients.empty? %>
    <div class="ingredients">
      <% @recipe.ingredients.each do |ingredient| %>
        <%= ingredient.text %><br>
      <% end %>
    </div>
  <% end %>

  <% unless @recipe.instructions.blank? %>
    <p><%= simple_format(@recipe.instructions) %></p>
  <% end %>

  <% unless @recipe.ocr_raw_text.blank? %>
    <textarea id="ocr-raw-text"><%= @recipe.ocr_raw_text %></textarea>
  <% end %>

</div>

<br style="clear: both;">

<div style="margin-top: 20px;">
  <p class="light">
    <% if @recipe.source.blank? %>
      Created <%= time_ago_in_words(@recipe.created_at) + " ago" %>
    <% else %>
      <%= @recipe.source + " " + time_ago_in_words(@recipe.created_at) + " ago" %>
    <% end %>
    |
    <%= link_to 'Delete this recipe', @recipe, method: :delete, data: { confirm: 'Are you sure? There is no going back!' } %>
  </p>
</div>

</div>

app/views/recipes/update.html.erb
<h1>Recipes#update</h1>
<p>Find me in app/views/recipes/update.html.erb</p>

app/views/users/index.html.erb
<h3>Users</h3>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>